---

- name: windows-networking-gui
  hosts: windows_gui
  gather_facts: no

  tasks:
  - name: set hostname
    win_hostname:
      name: "{{ hostname }}"

  - name: create deploy directory
    win_file:
      path: C:\480
      state: directory
  - name: load from jinja template
    win_template:
      src: files/windows/dhcp-to-static.ps1.j2
      dest: C:\480\dhcp-to-static.ps1.j2
  - name: run the script
    async: 10
    poll: 0
    win_shell:
      C:\480\dhcp-to-static.ps1