---
- name: Download Software
  hosts: windows_workstation
  gather_facts: no

  tasks:
  - name: Install 7zip
    win_chocolatey:
      name: 7zip
      state: present
      
  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present

  - name: Install visual studio code
    win_chocolatey:
      name: vscode
      state: present

  - name: Install Putty
    win_chocolatey:
      name: putty
      state: present

  - name: Install python3
    win_chocolatey:
      name: python3
      state: present

  - name: Install git
    win_chocolatey:
      name: git
      state: present

  - name: Install wireshark
    win_chocolatey:
      name: wireshark
      state: present
    
  