---

- name: windows-networking
  hosts: domain_controller
  gather_facts: no
  vars_prompt:
  - name: adminpassword
    prompt: "What will be the password for the local and domain admin?"
    private: yes

  tasks:
  - name: set the local admin
    win_user:
      name: Administrator
      password: "{{ adminpassword }}"
      state: present
      password_never_expires: yes

  - name: change time zone
    win_timezone:
        timezone: Eastern Standard Time
    register: timezone

  - name: set hostname
    win_hostname:
      name: "{{ hostname }}"

  - name: create deploy directory
    win_file:
      path: C:\480
      state: directory
  - name: load from jinja template
    win_template:
      src: files/windows/dhcp-to-static.ps1.j2
      dest: C:\480\dhcp-to-static.ps1.j2
  - name: run the script
    async: 10
    poll: 0
    win_shell:
      C:\480\dhcp-to-static.ps1