---
  - name: Create a blue team domain controller
    hosts: domain_controller
    gather_facts: no
    vars_prompt:
    - name: adminpassword
      prompt: "What will the safe mode password be?"
      private: yes

    tasks:
      - name: create new forest
        win_domain:
            dns_domain_name: "{{ domain }}"
            safe_mode_password: "{{ adminpassword }}"
        register: domain_install

      - name: reboot after creation
        when: domain_install.reboot_required
        win_reboot:
          connect_timeout: 15
          post_reboot_delay: 15
          reboot_timeout: 200
          msg: "server config in process: rebooting....."

      - name: wait for system
        wait_for_connection:
          timeout: 900
      - name: pause for 7 minutes
        pause:
          minutes: 7
      - name: dns config
        win_shell: |
          Add-DnsServerForwarder -IPAddress "{{ gateway }}" -PassThru